### PR TITLE
First draft of tuples lab

### PR DESCRIPTION
**Pull request by mdippery**
cc: @JimCampagno @AnnJohn

### CODE REVIEW

**Comment by JimCampagno** [comment]
Perfecto. 👍 

Only thing I ask moving forward with playground labs is the following:
- Create a solution branch that includes the solution file + the answers.
- Your branch should exclude the solution file and only have the main file which will become the master branch (the ones the student see).

Actually, the same process should be applied to all labs (Xcode & Playground) with regards to the solution branch. Moving forward of course.. I got this one.

Maybe write something like this at the bottom of the main playground file on what will become the master branch (not the solution branch one of course):

blah

``` swift
// Check out the solution branch to see a link here (in this same spot) that will take you to the answers to the above problems.
```

@mdippery

**Comment by mdippery** [comment]
Should the lab playgrounds still have multiple pages, or should the they be single-page playgrounds?

**Comment by JimCampagno** [comment]
Hmm. The one not that will live on the master branch should be one page. The one that lives on the solution branch.. we have two options.
1. Make it multiple pages to then have them navigate to the answers (in playground) in the left pane by selecting the solution.swift file, or have them drag down to the bottom of that page to see the solution link (which brings them to the solution.swift file)
2. We provide the solution in the readme.md file OF the solution branch to not have to create multiple pages in the playground file just for the solution branch.

Thoughts?

@mdippery

**Comment by mdippery** [comment]
I'd say, probably have a 2-page playground in the solution branch. That sounds like a good idea.

**Pull request merged**
